icoffe/apps/contactenos/urls.py
from django.conf.urls import url
from .views import ContactoView, AgradecimientoView

urlpatterns = [
    url(r'^buzon/$', ContactoView.as_view(), name='buzon'),
    url(r'^gracias/$', AgradecimientoView.as_view(), name='gracias')
]

icoffe/icoffe/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from apps.ventas.views import demo_vista_basica, carta_productos

urlpatterns = [
    url(r'^$', carta_productos, name='inicio'),
    url(r'^demo/$', demo_vista_basica),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^contactenos/', include('apps.contactenos.urls', namespace='contactenos')),
    url(r'^reserva/', include('apps.reservas.urls', namespace='reserva')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += [
        url(r'^demo/', include('apps.ejemplos.urls', namespace='ejemplos')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

icoffe/templates/layouts/sistema.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="{% static 'custom/' %}img/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Icoffe
  </a>
</nav>
<div class="container-fluid">
  {% block contenedor %}{% endblock %}
</div>
{% endblock %}

icoffe/templates/layouts/website.html
{% extends 'base.html' %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">INEICOFFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inicio' %}">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contactenos:buzon' %}">Buzon de Sugerencias</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Buscar">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
</nav>
<div class="container-fluid">
  {% block contenedor %}{% endblock %}
</div>

{% endblock %}